spring:
  data:
    elasticsearch:
      host: localhost:9200
      username : elastic
      password: nhndev2024
      socket-timeout: 60000
      connect-timeout: 5000
      connection-request-timeout: 300000
